"""initial schema

Revision ID: a3855278d889
Revises: 
Create Date: 2026-06-11 06:34:39.049829

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'a3855278d889'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Extensao necessaria para o indice GIN trigram (fuzzy match de nomes)
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.create_table('analysis_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('props_count', sa.Integer(), nullable=False),
    sa.Column('strong_count', sa.Integer(), nullable=False),
    sa.Column('games_count', sa.Integer(), nullable=False),
    sa.Column('quota_used', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(length=120), nullable=False),
    sa.Column('market_key', sa.String(length=60), nullable=False),
    sa.Column('line', sa.Float(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('odd_decimal', sa.Float(), nullable=False),
    sa.Column('ev_pct', sa.Float(), nullable=False),
    sa.Column('kelly_pct', sa.Float(), nullable=False),
    sa.Column('stake', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('result', sa.String(length=10), nullable=True),
    sa.Column('profit_loss', sa.Float(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bets_status', 'bets', ['status'], unique=False)
    op.create_table('line_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('player_name', sa.String(length=120), nullable=False),
    sa.Column('market_key', sa.String(length=60), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('line_opened', sa.Float(), nullable=False),
    sa.Column('line_current', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_date', 'player_name', 'market_key', 'direction', name='uq_line_snapshot')
    )
    op.create_index('ix_line_game_date', 'line_snapshots', ['game_date'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=80), nullable=False),
    sa.Column('abbreviation', sa.String(length=5), nullable=False),
    sa.Column('nba_api_id', sa.Integer(), nullable=True),
    sa.Column('espn_id', sa.String(length=20), nullable=True),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.Column('conference', sa.String(length=10), nullable=True),
    sa.Column('division', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abbreviation'),
    sa.UniqueConstraint('full_name')
    )
    op.create_table('analyzed_props',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(length=120), nullable=False),
    sa.Column('team', sa.String(length=5), nullable=False),
    sa.Column('opponent', sa.String(length=5), nullable=False),
    sa.Column('market_key', sa.String(length=60), nullable=False),
    sa.Column('market_label', sa.String(length=40), nullable=False),
    sa.Column('line', sa.Float(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('odd_decimal', sa.Float(), nullable=False),
    sa.Column('odd_implied_prob', sa.Float(), nullable=False),
    sa.Column('bookmaker', sa.String(length=40), nullable=False),
    sa.Column('all_odds', sa.JSON(), nullable=False),
    sa.Column('true_probability', sa.Float(), nullable=False),
    sa.Column('ev_percent', sa.Float(), nullable=False),
    sa.Column('kelly_fraction', sa.Float(), nullable=False),
    sa.Column('classification', sa.String(length=10), nullable=False),
    sa.Column('avg_stat_last10', sa.Float(), nullable=False),
    sa.Column('games_over_line_pct', sa.Float(), nullable=False),
    sa.Column('last5_values', sa.JSON(), nullable=False),
    sa.Column('def_rating_opponent', sa.Float(), nullable=False),
    sa.Column('pace', sa.Float(), nullable=False),
    sa.Column('minutes_avg', sa.Float(), nullable=False),
    sa.Column('projected_min', sa.Float(), nullable=True),
    sa.Column('min_boost_pct', sa.Float(), nullable=False),
    sa.Column('dvp_rank', sa.Integer(), nullable=False),
    sa.Column('dvp_total', sa.Integer(), nullable=False),
    sa.Column('team_injuries', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['analysis_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_props_player_market', 'analyzed_props', ['player_name', 'market_key'], unique=False)
    op.create_index('ix_props_snapshot', 'analyzed_props', ['snapshot_id'], unique=False)
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nba_api_game_id', sa.String(length=20), nullable=True),
    sa.Column('espn_event_id', sa.String(length=20), nullable=True),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('season', sa.String(length=10), nullable=False),
    sa.Column('season_type', sa.String(length=20), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=True),
    sa.Column('away_team_id', sa.Integer(), nullable=True),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('is_playoff', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('espn_event_id'),
    sa.UniqueConstraint('nba_api_game_id')
    )
    op.create_index('ix_games_date', 'games', ['game_date'], unique=False)
    op.create_index('ix_games_season', 'games', ['season'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('normalized_name', sa.String(length=120), nullable=False),
    sa.Column('nba_api_id', sa.Integer(), nullable=True),
    sa.Column('espn_id', sa.String(length=20), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('espn_id'),
    sa.UniqueConstraint('nba_api_id')
    )
    op.create_index(op.f('ix_players_normalized_name'), 'players', ['normalized_name'], unique=False)
    op.create_index('ix_players_normalized_name_trgm', 'players', ['normalized_name'], unique=False, postgresql_using='gin', postgresql_ops={'normalized_name': 'gin_trgm_ops'})
    op.create_table('player_game_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('season', sa.String(length=10), nullable=False),
    sa.Column('season_type', sa.String(length=20), nullable=False),
    sa.Column('is_playoff', sa.Boolean(), nullable=False),
    sa.Column('home_away', sa.String(length=5), nullable=True),
    sa.Column('opponent_abbr', sa.String(length=5), nullable=True),
    sa.Column('team_abbr', sa.String(length=5), nullable=True),
    sa.Column('team_score', sa.Integer(), nullable=True),
    sa.Column('opp_score', sa.Integer(), nullable=True),
    sa.Column('margin', sa.Integer(), nullable=True),
    sa.Column('min_played', sa.Float(), nullable=True),
    sa.Column('pts', sa.Float(), nullable=True),
    sa.Column('reb', sa.Float(), nullable=True),
    sa.Column('ast', sa.Float(), nullable=True),
    sa.Column('fg3m', sa.Float(), nullable=True),
    sa.Column('blk', sa.Float(), nullable=True),
    sa.Column('stl', sa.Float(), nullable=True),
    sa.Column('tov', sa.Float(), nullable=True),
    sa.Column('fgm', sa.Float(), nullable=True),
    sa.Column('fga', sa.Float(), nullable=True),
    sa.Column('fg3a', sa.Float(), nullable=True),
    sa.Column('ftm', sa.Float(), nullable=True),
    sa.Column('fta', sa.Float(), nullable=True),
    sa.Column('oreb', sa.Float(), nullable=True),
    sa.Column('dreb', sa.Float(), nullable=True),
    sa.Column('pf', sa.Float(), nullable=True),
    sa.Column('plus_minus', sa.Float(), nullable=True),
    sa.Column('pra', sa.Float(), nullable=True),
    sa.Column('pr', sa.Float(), nullable=True),
    sa.Column('pa', sa.Float(), nullable=True),
    sa.Column('ra', sa.Float(), nullable=True),
    sa.Column('stocks', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'game_id', name='uq_player_game')
    )
    op.create_index('ix_pgl_player_date', 'player_game_logs', ['player_id', 'game_date'], unique=False)
    op.create_index('ix_pgl_player_season', 'player_game_logs', ['player_id', 'season'], unique=False)
    op.create_index('ix_pgl_season', 'player_game_logs', ['season'], unique=False)
    op.create_table('sync_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('last_game_date', sa.Date(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('seasons_backfilled', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_states')
    op.drop_index('ix_pgl_season', table_name='player_game_logs')
    op.drop_index('ix_pgl_player_season', table_name='player_game_logs')
    op.drop_index('ix_pgl_player_date', table_name='player_game_logs')
    op.drop_table('player_game_logs')
    op.drop_index('ix_players_normalized_name_trgm', table_name='players', postgresql_using='gin', postgresql_ops={'normalized_name': 'gin_trgm_ops'})
    op.drop_index(op.f('ix_players_normalized_name'), table_name='players')
    op.drop_table('players')
    op.drop_index('ix_games_season', table_name='games')
    op.drop_index('ix_games_date', table_name='games')
    op.drop_table('games')
    op.drop_index('ix_props_snapshot', table_name='analyzed_props')
    op.drop_index('ix_props_player_market', table_name='analyzed_props')
    op.drop_table('analyzed_props')
    op.drop_table('teams')
    op.drop_index('ix_line_game_date', table_name='line_snapshots')
    op.drop_table('line_snapshots')
    op.drop_index('ix_bets_status', table_name='bets')
    op.drop_table('bets')
    op.drop_table('analysis_snapshots')
    # ### end Alembic commands ###
